loanProject/loanApp/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import  *
from .views import CustomPasswordResetView, CustomPasswordResetDoneView

urlpatterns = [
    path('home', home, name='home'),
    path('user-dashboard', user_dashboard),
    path('applicants',applicants, name='applicants'),
    path('information',information, name='information'),
    path('delete', remove_user, name="remove_user"),
    path('performance',performance, name='performance'),
    path('reports',reports, name='reports'),
    path('predictions',predictions, name='predictions'),
    path('chat-assistance/',chat_assistance, name='chat_assistance'),
    path('loan-history',loan_history, name='loan_history'),
    path('aboutUs',aboutUs, name='aboutUs'),
    path('view-profile',view_profile, name='view_profile'),
    path('reset-password',reset_password, name='reset_password'),
    path('create-application',create_applicant, name='create_applicant'),
    path('', welcome, name='welcome'),
    path('login/', login_view, name ='login'),
    path('accounts/', include('allauth.urls')),
    path("profile/<str:id>/", profile, name="profile"),
    path("update/", update, name="update"),
    path('accounts/password-reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('register/', register, name='register'),
    path('logout_user',logout_user, name='logout'),
    path('deleteImage', delete_image, name='delete_image')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loanProject/loanProject/urls.py
from django.urls import path,include

from loanApp.views import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from loanApp.views import login_view
from allauth.account.views import PasswordResetView, PasswordResetDoneView
from loanApp.views import profile

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('loanApp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loanProject/loanApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import shortuuid


class CustomUser(AbstractUser):
    is_admin= models.BooleanField('Is admin', default=False)
    is_customer = models.BooleanField('Is customer', default=False)
    image = models.FileField(upload_to='', null=True, blank=True)


class SavedModel(models.Model):
    name = models.CharField(max_length=50)
    file_path = models.CharField(max_length=255)
    
    

class UserDetail(models.Model):
    userID = models.AutoField(primary_key=True)
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)
    job = models.CharField(max_length=30, null=True)
    salary = models.FloatField(null=True)
    image = models.FileField(upload_to='profile', null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True) 
    
    def __str__(self):
        return self.firstName + " " + self.lastName

class LoanApplicant(models.Model):
    LoanID = models.CharField(max_length=12, primary_key=True, default=shortuuid.uuid)
    Age = models.IntegerField() 
    Income = models.FloatField()
    LoanAmount = models.FloatField()
    CreditScore = models.IntegerField()
    MonthsEmployed = models.IntegerField()
    LoanTerm = models.IntegerField()
    DTIRatio = models.FloatField()
    Default = models.IntegerField(null=True, blank=True)
    

loanProject/templates/anonymousProfile.html
<!-- anonymous_profile.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anonymous Profile</title>
</head>
<body>

    <p>Welcome! To access your profile, please <a href="{% url 'login' %}">log in</a>.</p>

</body>
</html>

loanProject/templates/custom_password_reset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: 'Source Sans Pro', sans-serif;
      background-color: rgb(214, 142, 219);
      margin: 0;
    }

    .container {
      max-width: 400px;
      margin: 0 auto;
      padding: 20px;
      background-color: rgb(61, 162, 234);
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin-top: 50px;
      text-align: center;
      border-radius: 8px; 
    }

    h2 {
      color: #333;
    }

    p {
      color: #555;
    }

    .password-reset-form {
      margin-top: 20px;
    }

    .password-reset-form label {
      display: block;
      margin-bottom: 8px;
      color: #333;
    }

    .password-reset-form input {
      width: 100%;
      padding: 10px;
      margin-bottom: 15px;
      box-sizing: border-box;
      border: 1px solid #2b70d2;
      border-radius: 4px;
    }

    .password-reset-form button {
      background-color: rgb(214, 142, 219);
      color: #fff;
      padding: 10px 15px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    .password-reset-form button:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="container">
    <h2>Password Reset</h2>
    <p>Enter your email address below, and we'll send you a link to reset your password.</p>
    
    <form method="post" class="password-reset-form">
      {% csrf_token %}
      <label for="{{ form.email.id_for_label }}"></label>
      {{ form.email }}
      
      <button type="submit">Reset Password</button>
    </form>
  </div>
</body>
</html>

loanProject/templates/custom_password_reset_done.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      font-family: 'Source Sans Pro', sans-serif;
      background-color: rgb(61, 162, 234);
      margin: 0; 
    }

    .container {
      width: 300px;
      margin: 0 auto;
      padding: 20px;
      background-color: #fff;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin-top: 50px;
      border-radius: 8px; /* Add border-radius for rounded corners */
      text-align: center; /* Center the content horizontally */
    }

    h2 {
      color: #333;
    }

    p {
      color: #555;
    }
  </style>
</head>
<body>
  <div class="container">
    <h2>Password Reset Requested</h2>
    <p>We've sent you an email with instructions on how to reset your password. Please check your inbox.</p>
    <p>If you don't receive the email within a few minutes, please check your spam folder.</p>
  </div>
</body>
</html>

loanProject/templates/home.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{%static 'assets/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{%static 'assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{%static 'assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{%static 'assets/plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'assets/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{%static 'assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{%static 'assets/plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{%static 'assets/plugins/summernote/summernote-bs4.min.css' %}">

    <title>AI Loan</title>

    <style>
      body {
        background-color: #e9ecef;
      }

      .nav {
        background-color: #9616BD;
      }

      .link {
        padding-right: 2em;
        font-size: 1.25em;
      }

      .nav-link {
        color: white;
      }

      .nav-link:hover {
        color: rgb(200, 200, 200);
      }

      .box {
        display: inline-block;
        width: 50%;
        float: left;
        padding: 2em;
      }

      .home {
        padding: 2em;
      }

      .form {
        background-color: rgb(200, 200, 240);
        background-color: white;
        padding: 2em;
        border-radiums: 1em;
        text-align: center;
        width: 25%;
        margin-left: 15em;
      }

      .left {
        width: 55%;
      }

      form {
        margin-top: 2em;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm nav">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="{%static 'assets/dist/img/AILOAN-removebg.png' %}" height="35%" width="35%">
        </a>

        <ul class="nav navbar-nav navbar-right">
          <li class="link"><a href="/login" class="nav-link">Login</a></li>
          <li class="link"><a href="/register" class="nav-link">Sign Up</a></li>
        </ul>
      </div>
    </nav>

    <div class="home">
      <div class="box left">
        <h1>Welcome to AiLoan</h1>
        <p>We help you simplify your loan application and eligibility process. Using AILoan, as a bank customer, you can quickly discover if you are eligible for a loan with your bank. As a bank admin, you can quickly check if your applicants are eligible for a loan. With AI, we help you reduce the risks, processing time and provide reliable feedback.</p>
        <p><b>Are you interested?</b> <a href="/register">Sign up</a> right now!</p>
      </div>

      <div class="box form">
        <h1>Already have an account?</h1>
        <h3>Sign right in!</h3>
        <span class="mb-0 text-muted">
          {% if msg %}
              {{ msg | safe }}
          {% endif %}
        </span>
        <form method="post">
          {% csrf_token %}
          <div class="input-group mb-3">
              {{ form.username }}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-envelope"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
              {{ form.password }}
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              <div class="forgot-password">
                  <a href="{% url 'password_reset' %}" style="color: #090303;">Forgot Password?</a>
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block">Log In</button>
            </div>
            <!-- /.col -->
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

loanProject/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AILOAN | Log in</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%static 'assets/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{%static 'assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static 'assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static 'assets/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'assets/dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <img src="{%static 'assets/dist/img/AILOAN-removebg.png' %}">
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Log in to start your session</p>
      <form method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{ form.username }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            {{ form.password }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="forgot-password">
                <a href="{% url 'password_reset' %}" style="color: #090303;">Forgot Password?</a>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Log In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder="Username";
    form_fields[2].placeholder="Password";
    for (var field in form_fields){
      form_fields[field].className += ' form-control'
    }
  
  </script>
<!-- jQuery -->
<script src="{%static '../../plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{%static '../../plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static '../../dist/js/adminlte.min.js' %}"></script>
</body>
</html>

loanProject/templates/profile.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap 4 files -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    
        <style>
        body {
            text-align: center;
        }
        </style>
    </head>
    <body>
        {%csrf_token%}
        {% if found %}
        <div class="jumbotron">
            <h1>Welcome {{fname}} {{lname}}!</h1>
            <p><b>Username: </b> {{usrnm}}</p>
            <p><b>Email: </b> {{email}}</p>
            <p><b>Position: </b> {{position}}</p>

            <a href="update/">Update</a>
        </div>

        {% else %}
            <h1>{{msg}}</h1>
        {% endif %}
    </body>
</html>

loanProject/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Registration Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%static 'assets/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{%static 'assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{%static 'assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{%static 'assets/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{%static 'assets/dist/css/adminlte.min.css' %}">
  <style>
    .control--checkbox {
      transform: scale(0.8); 
      margin-right: 5px; 
    }
  </style>
  
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <img src="{%static 'assets/dist/img/AILOAN-removebg.png' %}">
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new account</p>
      <span class="mb-0 text-muted">
        {% if msg %}
            {{ msg | safe }}
        {% else %}
            Sign up
        {% endif %}
      </span>
      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            {{ form.username }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            {{ form.email}}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            {{ form.password1 }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            {{ form.password2 }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="d-flex mb-5 align-items-center">
          <label for="id_is_admin" class="control control--checkbox mb-0 mr-3">
            <span class="caption">Admin</span>
            {{ form.is_admin }}
            <div class="control__indicator" id="adminCheckbox"></div>
          </label>
        
          <label for="id_is_customer" class="control control--checkbox mb-0">
            <span class="caption">Customer</span>
            {{ form.is_customer }}
            <div class="control__indicator" id="customerCheckbox"></div>
          </label>
        </div>
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
      </form>

      <a href="/login" class="text-center">I already have have an account</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->


<script>
  document.addEventListener('DOMContentLoaded', function () {
    const adminCheckbox = document.getElementById('id_is_admin');
    const customerCheckbox = document.getElementById('id_is_customer');

    adminCheckbox.addEventListener('change', function () {
      if (this.checked) {
        customerCheckbox.checked = false;
      }
    });

    customerCheckbox.addEventListener('change', function () {
      if (this.checked) {
        adminCheckbox.checked = false;
      }
    });
  });
</script>
<script>
  var form_fields = document.getElementsByTagName('input')
  form_fields[1].placeholder="Username";
  form_fields[2].placeholder="Email";
  form_fields[3].placeholder="Password";
  form_fields[4].placeholder="Confirm password";

  for (var field in form_fields){
    form_fields[field].className += ' form-control'
  }

</script>
<!-- jQuery -->
<script src="{%static '../../plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{%static '../../plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{%static '../../dist/js/adminlte.min.js' %}"></script>

</body>
</html>

loanProject/templates/updateUser.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap 4 files -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <title>Edit {{user}}</title>
    
        <style>
            .input {
                margin: 1em;
            }
        </style>
    </head>
    <body>
        <form action="" method="post">
            {% csrf_token %}
           <div class="jumbotron">
            <div class="name input">
                <h3 style="padding-bottom:1em">Update {{user}}</h3>
                <label class="my_class" for="{{ form.fname.auto_id }}"></label>
                {{ form.fname }}
                <label class="my_class" for="{{ form.lname.auto_id }}"></label>
                {{ form.lname }}
            </div>
            <div class="email input">
                <label class="my_class" for="{{ form.email.auto_id }}"></label>
                {{ form.email }}
            </div>
            <input type="submit" value="OK">
        </div>
        </form>
    </body>
</html>

loanProject/templates/welcome.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>AILone</title>
  </head>
  <body>
  <div class="content">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4">
                    <div class="horizontal-align">
                        <img class="animation__shake" src="{% static 'assets/dist/img/ailoan_logo_short.png' %}" alt="ai_loan_logo" height="60" width="60"> 
                        <h1>Welcome to AILone</h1>
                    </div>
                  </div>
                  <div>
                    <label>We help you simplify your loan application and eligibility process.
                           Using AILoan, as a bank customer, you can quickly discover if you are eligible for a loan 
                           with your bank. As a bank admin, you can quickly check if your applicants are eligible for
                           a loan. With AI, we help you reduce the risks, processing time and provide reliable feedback.
                    </label>
                  </div>
                  <label>Log in if you already have registered!</label>
                  <div class="form-group last mb-4">
                      <div><button class="btn btn-pill text-white btn-block btn-primary"><a href="{% url 'login' %}">login</a></button></div>
                  </div>
                  <label>If not register here!</label>
                  <div class="form-group last mb-4">
                      <div><button class="btn btn-pill text-white btn-block btn-primary"><a href="{% url 'register' %}">register</a></button></div>
                  </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  </div>
  </body>
</html>
/
<style>
.horizontal-align img,
.horizontal-align h1 {
    display: inline-block;
    vertical-align: middle; /* vertically alignment */
}

</style>